# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = HandwritingPadTest
QT += core widgets gui
CONFIG += debug

HEADERS += ./handwritingpadtest.h \
    ./HandwritingPad.h \
    ./TestLabel.h
SOURCES += ./main.cpp \
    ./handwritingpadtest.cpp \
    ./HandwritingPad.cpp \
    ./TestLabel.cpp
FORMS += ./handwritingpadtest.ui
